baseURL = "https://masukomi.github.io/private_comments/"
languageCode = "en-us"
title = "Private Comments"
theme = "docuapi"
metaDataFormat = "yaml"


# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "javascript"
name= "JavaScript"
[[params.language_tabs]]
key = "shell"
name = "Shell" 
# [[params.language_tabs]]
# key = "go"
# name = "Go" 
# [[params.language_tabs]]
# key = "ruby"
# name = "Ruby"
# [[params.language_tabs]]
# key = "python"
# name = "Python"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Private Comments"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


# [languages.nn]
# languageName = "Nynorsk"
# weight = 1
# title = "DocuAPI-døme"
#
# # Left sidebar footer items. Use HTMl or Markdown.
# toc_footers = [ 
# "<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
# "Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
# "Hugo Theme av [bep](https://github.com/bep)"
# ]
#
# [languages.nn.blackfriday]
# # Norwegian uses angled quotes
# angledQuotes = true
# hrefTargetBlank = true

