name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - if: matrix.runs-on == 'macos-latest'
        run: "cd ./src && ./build.sh"
      - if: matrix.runs-on == 'ubuntu-latest'
        run: "./linux/make.release.sh"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*.tgz"
